// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbD9YAkhFnGzeSAxjNy6sw5h_8YcreCIE',
    appId: '1:668130596040:web:9829ff4e475108115d41fd',
    messagingSenderId: '668130596040',
    projectId: 'final-mobile-9b051',
    authDomain: 'final-mobile-9b051.firebaseapp.com',
    storageBucket: 'final-mobile-9b051.firebasestorage.app',
    measurementId: 'G-EK7LCD58QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexFdfB2J1daJuGhpvEiwjCWrPVgfhTEk',
    appId: '1:668130596040:android:c292d421cf1ccda25d41fd',
    messagingSenderId: '668130596040',
    projectId: 'final-mobile-9b051',
    storageBucket: 'final-mobile-9b051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqdhgIG0GqfRAk81IW3CrYUX9eNPhktH0',
    appId: '1:668130596040:ios:c69868687ab955e95d41fd',
    messagingSenderId: '668130596040',
    projectId: 'final-mobile-9b051',
    storageBucket: 'final-mobile-9b051.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqdhgIG0GqfRAk81IW3CrYUX9eNPhktH0',
    appId: '1:668130596040:ios:c69868687ab955e95d41fd',
    messagingSenderId: '668130596040',
    projectId: 'final-mobile-9b051',
    storageBucket: 'final-mobile-9b051.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbD9YAkhFnGzeSAxjNy6sw5h_8YcreCIE',
    appId: '1:668130596040:web:5f2450f25d3184975d41fd',
    messagingSenderId: '668130596040',
    projectId: 'final-mobile-9b051',
    authDomain: 'final-mobile-9b051.firebaseapp.com',
    storageBucket: 'final-mobile-9b051.firebasestorage.app',
    measurementId: 'G-KKLQ036CPL',
  );
}
